services:
  mysql:
    image: mysql:8.0
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: nghia123456
      MYSQL_DATABASE: auctions
      MYSQL_USER: nghia64582
      MYSQL_PASSWORD: nghia123456
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/data  # Mount SQL script
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

  app:
    build:
      dockerfile: Dockerfile
    container_name: spring
    hostname: spring
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/auctions?useSSL=false&allowPublicKeyRetrieval=true&failOverReadOnly=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: nghia123546
    ports:
      - "8080:8080"
    links:
      - mysql:mysql


volumes:
  redis-data:
    driver: local
  mysql-data:
    driver: local