services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nghia123456
      MYSQL_DATABASE: auctions
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/data  # Mount SQL script
  redis:
    image: redis:latest
    container_name: my-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
  init-script:
    build: .
    depends_on:
      - mysql
    command: ["sh", "-c", "sleep 10 && python /app/sql_scripts/data_creator/main.py"]
  app:
    build: .
    container_name: spring_boot_app
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/auctions
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: nghia123546
    ports:
      - "8080:8080"

volumes:
  redis-data:
    driver: local
  mysql-data:
    driver: local