spring:
    application:
        name: online_auction_platform

    batch:
        jdbc:
            initialize-schema: always

    #  datasource:
    #    url: jdbc:mysql://mysql:3306/auctions?useSSL=false&allowPublicKeyRetrieval=true
    #    username: nghia64582
    #    password: nghia123456
    #    jpa:
    #      database-platform: org.hibernate.dialect.MySQL8Dialect

    datasource:
        url: jdbc:mysql://localhost:3306/auctions?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        username: root
        password: nghia123456
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update  # Change to 'none' if using migrations
        show-sql: true  # Enable to print SQL queries in logs
    
    security:
        user:
            name: nghia64582
            password: nghia123456

google:
    oauth:
        client:
            id: 845416159696-1r3jlfhjbt0chvm336a7hg86nern92gl.apps.googleusercontent.com
            secret: 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
        redirect:
            uri: http://localhost:8080/api/auth/google
        token:
            uri: https://oauth2.googleapis.com/token
        userinfo:
            uri: https://www.googleapis.com/oauth2/v3/userinfo