spring:
  application:
    name: online_auction_platform

  batch:
    jdbc:
      initialize-schema: always

#  datasource:
#    url: jdbc:mysql://localhost:3306/auctions?useSSL=false&allowPublicKeyRetrieval=true
#    username: root
#    password: nghia123456
#    jpa:
#      database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysqldb://localhost:3306/auctions?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: nghia123456
    jpa:
      database-platform: org.hibernate.dialect.mysqlDBDialect
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.mysqlDBDialect
  security:
    user:
      name: nghia64582
      password: nghia123456


  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # Show formatted SQL queries in the console

google:
  oauth:
    client:
      id: 845416159696-1r3jlfhjbt0chvm336a7hg86nern92gl.apps.googleusercontent.com
      secret: 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
    redirect:
      uri: http://localhost:8080/api/auth/google
    token:
      uri: https://oauth2.googleapis.com/token
    userinfo:
      uri: https://www.googleapis.com/oauth2/v3/userinfo