spring:
    application:
        name: online_auction_platform

    batch:
        jdbc:
            initialize-schema: always

    datasource:
        url: jdbc:mysql://localhost:3306/auctions?useSSL=false
        username: root
        password: admin123456

    security:
        user:
            name: nghia64582
            password: nghia123456

    data:
        redis:
            host: 127.0.0.1
            port: 6379

    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true  # Show formatted SQL queries in the console

google:
    oauth:
        client:
            id: 845416159696-1r3jlfhjbt0chvm336a7hg86nern92gl.apps.googleusercontent.com
            secret: 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
        redirect:
            uri: http://localhost:8080/api/auth/google
        token:
            uri: https://oauth2.googleapis.com/token
        userinfo:
            uri: https://www.googleapis.com/oauth2/v3/userinfo
logging:
    level:
        org:
            hibernate: info
            hibernate.SQL: debug
            hibernate.orm.jdbc.bind: trace
            hibernate.stat: debug
            hibernate.SQL_SLOW: info
            hibernate.cache: debug